<?php

use Illuminate\Database\Seeder;
use App\Role;
use App\MUser;
class RoleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $admin = Role::create([
            'name' => 'Administrator',
            'c_config' => true,
            'r_config' => true,
            'u_config' => true,
            'd_config' => true,
            'c_mcoa' => true,
            'r_mcoa' => true,
            'u_mcoa' => true,
            'd_mcoa' => true,
            'c_generaljournal' => true,
            'r_generaljournal' => true,
            'u_generaljournal' => true,
            'd_generaljournal' => true,
            'c_fixedasset' => true,
            'r_fixedasset' => true,
            'u_fixedasset' => true,
            'd_fixedasset' => true,
            'c_cashbank' => true,
            'r_cashbank' => true,
            'u_cashbank' => true,
            'd_cashbank' => true,
            'c_cashbankincome' => true,
            'r_cashbankincome' => true,
            'u_cashbankincome' => true,
            'd_cashbankincome' => true,
            'c_cashbankoutcome' => true,
            'r_cashbankoutcome' => true,
            'u_cashbankoutcome' => true,
            'd_cashbankoutcome' => true,
            'c_cashbanktransfer' => true,
            'r_cashbanktransfer' => true,
            'u_cashbanktransfer' => true,
            'd_cashbanktransfer' => true,
            'c_purchase' => true,
            'r_purchase' => true,
            'u_purchase' => true,
            'd_purchase' => true,
            'c_payap' => true,
            'r_payap' => true,
            'u_payap' => true,
            'd_payap' => true,
            'c_purchaseorder' => true,
            'r_purchaseorder' => true,
            'u_purchaseorder' => true,
            'd_purchaseorder' => true,
            'c_supplier' => true,
            'r_supplier' => true,
            'u_supplier' => true,
            'd_supplier' => true,
            'c_categorysupplier' => true,
            'r_categorysupplier' => true,
            'u_categorysupplier' => true,
            'd_categorysupplier' => true,
            'c_sales' => true,
            'r_sales' => true,
            'u_sales' => true,
            'd_sales' => true,
            'c_salesquotation' => true,
            'r_salesquotation' => true,
            'u_salesquotation' => true,
            'd_salesquotation' => true,
            'c_payar' => true,
            'r_payar' => true,
            'u_payar' => true,
            'd_payar' => true,
            'c_customer' => true,
            'r_customer' => true,
            'u_customer' => true,
            'd_customer' => true,
            'c_categorycustomer' => true,
            'r_categorycustomer' => true,
            'u_categorycustomer' => true,
            'd_categorycustomer' => true,
            'c_categoryprice' => true,
            'r_categoryprice' => true,
            'u_categoryprice' => true,
            'd_categoryprice' => true,
            'c_goods' => true,
            'r_goods' => true,
            'u_goods' => true,
            'd_goods' => true,
            'c_units' => true,
            'r_units' => true,
            'u_units' => true,
            'd_units' => true,
            'c_brands' => true,
            'r_brands' => true,
            'u_brands' => true,
            'd_brands' => true,
            'c_goodstype' => true,
            'r_goodstype' => true,
            'u_goodstype' => true,
            'd_goodstype' => true,
            'c_goodssubtype' => true,
            'r_goodssubtype' => true,
            'u_goodssubtype' => true,
            'd_goodssubtype' => true,
            'c_warehouse' => true,
            'r_warehouse' => true,
            'u_warehouse' => true,
            'd_warehouse' => true,
            'c_employee' => true,
            'r_employee' => true,
            'u_employee' => true,
            'd_employee' => true,
            'c_employeelevel' => true,
            'r_employeelevel' => true,
            'u_employeelevel' => true,
            'd_employeelevel' => true,
            'c_currency' => true,
            'r_currency' => true,
            'u_currency' => true,
            'd_currency' => true,
            'c_tax' => true,
            'r_tax' => true,
            'u_tax' => true,
            'd_tax' => true,
            'c_employeepayment' => true,
            'r_employeepayment' => true,
            'u_employeepayment' => true,
            'd_employeepayment' => true,
            'c_branch' => true,
            'r_branch' => true,
            'u_branch' => true,
            'd_branch' => true,
            'c_user' => true,
            'r_user' => true,
            'u_user' => true,
            'd_user' => true,
            'r_stockreport' => true,
            'r_salesreport' => true,
            'r_salesinvoicereport' => true,
            'r_arreport' => true,
            'r_arcustomerreport' => true,
            'r_purchasereport' => true,
            'r_apreport' => true,
            'r_stockvaluereport' => true,
            'r_journal' => true,
            'r_ledger' => true  
        ]);
    }
}
