<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    protected $table = 'roles';
    protected $fillable = [
        'name',
        'c_config',
        'r_config',
        'u_config',
        'd_config',
        'c_mcoa',
        'r_mcoa',
        'u_mcoa',
        'd_mcoa',
        'c_generaljournal',
        'r_generaljournal',
        'u_generaljournal',
        'd_generaljournal',
        'c_fixedasset',
        'r_fixedasset',
        'u_fixedasset',
        'd_fixedasset',
        'c_cashbank',
        'r_cashbank',
        'u_cashbank',
        'd_cashbank',
        'c_cashbankincome',
        'r_cashbankincome',
        'u_cashbankincome',
        'd_cashbankincome',
        'c_cashbankoutcome',
        'r_cashbankoutcome',
        'u_cashbankoutcome',
        'd_cashbankoutcome',
        'c_cashbanktransfer',
        'r_cashbanktransfer',
        'u_cashbanktransfer',
        'd_cashbanktransfer',
        'c_purchase',
        'r_purchase',
        'u_purchase',
        'd_purchase',
        'c_payap',
        'r_payap',
        'u_payap',
        'd_payap',
        'c_purchaseorder',
        'r_purchaseorder',
        'u_purchaseorder',
        'd_purchaseorder',
        'c_supplier',
        'r_supplier',
        'u_supplier',
        'd_supplier',
        'c_categorysupplier',
        'r_categorysupplier',
        'u_categorysupplier',
        'd_categorysupplier',
        'c_sales',
        'r_sales',
        'u_sales',
        'd_sales',
        'c_salesquotation',
        'r_salesquotation',
        'u_salesquotation',
        'd_salesquotation',
        'c_payar',
        'r_payar',
        'u_payar',
        'd_payar',
        'c_customer',
        'r_customer',
        'u_customer',
        'd_customer',
        'c_categorycustomer',
        'r_categorycustomer',
        'u_categorycustomer',
        'd_categorycustomer',
        'c_categoryprice',
        'r_categoryprice',
        'u_categoryprice',
        'd_categoryprice',
        'c_goods',
        'r_goods',
        'u_goods',
        'd_goods',
        'c_units',
        'r_units',
        'u_units',
        'd_units',
        'c_brands',
        'r_brands',
        'u_brands',
        'd_brands',
        'c_goodstype',
        'r_goodstype',
        'u_goodstype',
        'd_goodstype',
        'c_goodssubtype',
        'r_goodssubtype',
        'u_goodssubtype',
        'd_goodssubtype',
        'c_warehouse',
        'r_warehouse',
        'u_warehouse',
        'd_warehouse',
        'c_employee',
        'r_employee',
        'u_employee',
        'd_employee',
        'c_employeelevel',
        'r_employeelevel',
        'u_employeelevel',
        'd_employeelevel',
        'c_currency',
        'r_currency',
        'u_currency',
        'd_currency',
        'c_tax',
        'r_tax',
        'u_tax',
        'd_tax',
        'c_employeepayment',
        'r_employeepayment',
        'u_employeepayment',
        'd_employeepayment',
        'c_branch',
        'r_branch',
        'u_branch',
        'd_branch',
        'c_user',
        'r_user',
        'u_user',
        'd_user',
        'r_stockreport',
        'r_salesreport',
        'r_salesinvoicereport',
        'r_arreport',
        'r_arcustomerreport',
        'r_purchasereport',
        'r_apreport',
        'r_stockvaluereport',
        'r_journal',
        'r_ledger',
        'r_departement',
    ];

    protected $casts = [
        'c_config' => 'boolean',
        'r_config' => 'boolean',
        'u_config' => 'boolean',
        'd_config' => 'boolean',
        'c_mcoa' => 'boolean',
        'r_mcoa' => 'boolean',
        'u_mcoa' => 'boolean',
        'd_mcoa' => 'boolean',
        'c_generaljournal' => 'boolean',
        'r_generaljournal' => 'boolean',
        'u_generaljournal' => 'boolean',
        'd_generaljournal' => 'boolean',
        'c_fixedasset' => 'boolean',
        'r_fixedasset' => 'boolean',
        'u_fixedasset' => 'boolean',
        'd_fixedasset' => 'boolean',
        'c_cashbank' => 'boolean',
        'r_cashbank' => 'boolean',
        'u_cashbank' => 'boolean',
        'd_cashbank' => 'boolean',
        'c_cashbankincome' => 'boolean',
        'r_cashbankincome' => 'boolean',
        'u_cashbankincome' => 'boolean',
        'd_cashbankincome' => 'boolean',
        'c_cashbankoutcome' => 'boolean',
        'r_cashbankoutcome' => 'boolean',
        'u_cashbankoutcome' => 'boolean',
        'd_cashbankoutcome' => 'boolean',
        'c_cashbanktransfer' => 'boolean',
        'r_cashbanktransfer' => 'boolean',
        'u_cashbanktransfer' => 'boolean',
        'd_cashbanktransfer' => 'boolean',
        'c_purchase' => 'boolean',
        'r_purchase' => 'boolean',
        'u_purchase' => 'boolean',
        'd_purchase' => 'boolean',
        'c_payap' => 'boolean',
        'r_payap' => 'boolean',
        'u_payap' => 'boolean',
        'd_payap' => 'boolean',
        'c_purchaseorder' => 'boolean',
        'r_purchaseorder' => 'boolean',
        'u_purchaseorder' => 'boolean',
        'd_purchaseorder' => 'boolean',
        'c_supplier' => 'boolean',
        'r_supplier' => 'boolean',
        'u_supplier' => 'boolean',
        'd_supplier' => 'boolean',
        'c_categorysupplier' => 'boolean',
        'r_categorysupplier' => 'boolean',
        'u_categorysupplier' => 'boolean',
        'd_categorysupplier' => 'boolean',
        'c_sales' => 'boolean',
        'r_sales' => 'boolean',
        'u_sales' => 'boolean',
        'd_sales' => 'boolean',
        'c_salesquotation' => 'boolean',
        'r_salesquotation' => 'boolean',
        'u_salesquotation' => 'boolean',
        'd_salesquotation' => 'boolean',
        'c_payar' => 'boolean',
        'r_payar' => 'boolean',
        'u_payar' => 'boolean',
        'd_payar' => 'boolean',
        'c_customer' => 'boolean',
        'r_customer' => 'boolean',
        'u_customer' => 'boolean',
        'd_customer' => 'boolean',
        'c_categorycustomer' => 'boolean',
        'r_categorycustomer' => 'boolean',
        'u_categorycustomer' => 'boolean',
        'd_categorycustomer' => 'boolean',
        'c_categoryprice' => 'boolean',
        'r_categoryprice' => 'boolean',
        'u_categoryprice' => 'boolean',
        'd_categoryprice' => 'boolean',
        'c_goods' => 'boolean',
        'r_goods' => 'boolean',
        'u_goods' => 'boolean',
        'd_goods' => 'boolean',
        'c_units' => 'boolean',
        'r_units' => 'boolean',
        'u_units' => 'boolean',
        'd_units' => 'boolean',
        'c_brands' => 'boolean',
        'r_brands' => 'boolean',
        'u_brands' => 'boolean',
        'd_brands' => 'boolean',
        'c_goodstype' => 'boolean',
        'r_goodstype' => 'boolean',
        'u_goodstype' => 'boolean',
        'd_goodstype' => 'boolean',
        'c_goodssubtype' => 'boolean',
        'r_goodssubtype' => 'boolean',
        'u_goodssubtype' => 'boolean',
        'd_goodssubtype' => 'boolean',
        'c_warehouse' => 'boolean',
        'r_warehouse' => 'boolean',
        'u_warehouse' => 'boolean',
        'd_warehouse' => 'boolean',
        'c_employee' => 'boolean',
        'r_employee' => 'boolean',
        'u_employee' => 'boolean',
        'd_employee' => 'boolean',
        'c_employeelevel' => 'boolean',
        'r_employeelevel' => 'boolean',
        'u_employeelevel' => 'boolean',
        'd_employeelevel' => 'boolean',
        'c_currency' => 'boolean',
        'r_currency' => 'boolean',
        'u_currency' => 'boolean',
        'd_currency' => 'boolean',
        'c_tax' => 'boolean',
        'r_tax' => 'boolean',
        'u_tax' => 'boolean',
        'd_tax' => 'boolean',
        'c_employeepayment' => 'boolean',
        'r_employeepayment' => 'boolean',
        'u_employeepayment' => 'boolean',
        'd_employeepayment' => 'boolean',
        'c_branch' => 'boolean',
        'r_branch' => 'boolean',
        'u_branch' => 'boolean',
        'd_branch' => 'boolean',
        'c_user' => 'boolean',
        'r_user' => 'boolean',
        'u_user' => 'boolean',
        'd_user' => 'boolean',
        'r_stockreport' => 'boolean',
        'r_salesreport' => 'boolean',
        'r_salesinvoicereport' => 'boolean',
        'r_arreport' => 'boolean',
        'r_arcustomerreport' => 'boolean',
        'r_purchasereport' => 'boolean',
        'r_apreport' => 'boolean',
        'r_stockvaluereport' => 'boolean',
        'r_journal' => 'boolean',
        'r_ledger' => 'boolean',
        'r_departement' => 'boolean',
    ];
}
